# Generated by Django 6.0.7 on 2026-08-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(help_text="e.g. 'order_placed', 'welcome_email'.", max_length=100, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Use {{ variable }} placeholders.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='FaizanMart', max_length=100)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=30)),
                ('currency_code', models.CharField(default='PKR', max_length=3)),
                ('currency_symbol', models.CharField(default='Rs', max_length=5)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Percentage, e.g. 5.00 for 5%.', max_digits=5)),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('cod_enabled', models.BooleanField(default=True)),
                ('stripe_enabled', models.BooleanField(default=False)),
                ('jazzcash_enabled', models.BooleanField(default=False)),
                ('easypaisa_enabled', models.BooleanField(default=False)),
                ('wallet_payments_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
