# Generated by Django 6.0.7 on 2026-08-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('order_update', 'Order Update'), ('vendor_approval', 'Vendor Approval'), ('admin_alert', 'Admin Alert'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
